// Generated by CoffeeScript 1.9.3
(function() {
  var strftime;

  strftime = require('strftime');

  exports.save = function(req, res) {
    var form;
    form = global.db.models.form;
    return global.db.Promise.resolve().then(function() {
      var data;
      if (req.body.jzdate.length === 0) {
        req.body.jzdate = null;
      }
      if (req.body.sydate.length === 0) {
        req.body.sydate = null;
      }
      if (req.body.bgdate.length === 0) {
        req.body.bgdate = null;
      }
      data = {
        number: req.body.id,
        company: req.body.company,
        jzDate: req.body.jzdate,
        syDate: req.body.sydate,
        bgDate: req.body.bgdate,
        data: JSON.stringify(req.body)
      };
      return form.create(data);
    }).then(function() {
      return res.render('index', {
        message: '保存成功'
      });
    })["catch"](function(err) {
      return res.render('index', {
        message: err.message
      });
    });
  };

  exports.show = function(req, res) {
    return global.db.Promise.resolve().then(function() {
      var form;
      form = global.db.models.form;
      return form.findAll();
    }).then(function(rows) {
      var ele, i, len;
      for (i = 0, len = rows.length; i < len; i++) {
        ele = rows[i];
        if (ele.syDate) {
          ele.sydate = strftime("%F", new Date(ele.syDate));
        }
        if (ele.bgDate) {
          ele.bgdate = strftime("%F", new Date(ele.bgDate));
        }
        if (ele.jzDate) {
          ele.jzdate = strftime("%F", new Date(ele.jzDate));
        }
      }
      return res.render('showAll', {
        report: rows
      });
    })["catch"](function(err) {
      console.log(err);
      return res.render('index', {
        message: err.message
      });
    });
  };

  exports.view = function(req, res) {
    return global.db.models.form.find({
      where: {
        number: req.query.number
      }
    }).then(function(data) {
      if (!data) {
        throw new Error('没找着这个表');
      }
      return res.render('view', {
        content: JSON.parse(data.data),
        number: data.number,
        company: data.company,
        sydate: strftime("%F", new Date(data.sydate)),
        bgdate: strftime("%F", new Date(data.bgdate)),
        jzdate: strftime("%F", new Date(data.jzdate))
      });
    })["catch"](function(err) {
      return res.render('index', {
        message: err.message
      });
    });
  };

  exports.edit = function(req, res) {
    console.log(req.body.id);
    return global.db.models.form.find({
      where: {
        number: req.body.id
      }
    }).then(function(ori) {
      var data, key;
      if (!ori) {
        throw new Error('没找着这个表');
      }
      if (req.body.jzdate.length === 0) {
        req.body.jzdate = null;
      }
      if (req.body.sydate.length === 0) {
        req.body.sydate = null;
      }
      if (req.body.bgdate.length === 0) {
        req.body.bgdate = null;
      }
      data = {
        number: req.body.id,
        company: req.body.company,
        jzDate: req.body.jzdate,
        syDate: req.body.sydate,
        bgDate: req.body.bgdate,
        data: JSON.stringify(req.body)
      };
      for (key in data) {
        ori[key] = data[key];
      }
      return ori.save();
    }).then(function() {
      return res.render('index', {
        message: '编辑成功'
      });
    })["catch"](function(err) {
      return res.render('index', {
        message: err.message
      });
    });
  };

}).call(this);

//# sourceMappingURL=utils.js.map
