// Generated by CoffeeScript 1.9.3
(function() {
  var Sequelize, models, path;

  Sequelize = require('sequelize');

  path = require('path');

  models = require('./models');

  module.exports = function(database, username, password, config) {
    var form, sequelize;
    sequelize = new Sequelize(database, username, password, config);
    form = sequelize["import"](path.join(__dirname, 'models/form'));
    return sequelize;
  };

}).call(this);

//# sourceMappingURL=index.js.map
