// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(sequelize, dataTypes) {
    return sequelize.define('form', {
      number: {
        type: dataTypes.INTEGER,
        allowNull: false,
        unique: true
      },
      company: {
        type: dataTypes.TEXT,
        allowNull: false,
        validate: {
          notEmpty: true
        }
      },
      jzDate: {
        type: dataTypes.DATE
      },
      syDate: {
        type: dataTypes.DATE
      },
      bgDate: {
        type: dataTypes.DATE
      },
      data: {
        type: dataTypes.TEXT('long')
      }
    });
  };

}).call(this);

//# sourceMappingURL=form.js.map
